function [fitresult, gof] = createFit(Time_Seconds_, X1)
%CREATEFIT(TIME_SECONDS_,X1)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input: Time_Seconds_ from dataName
%      Y Output: X1 from dataName
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-May-2023 00:14:17


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( Time_Seconds_, X1 );

% Set up fittype and options.
ft = fittype( 'poly9' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
legend( h, 'X1 vs. Time_Seconds_', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Time_Seconds_', 'Interpreter', 'none' );
ylabel( 'X1', 'Interpreter', 'none' );
grid on


